services:
  app-phpfpm:
    container_name: magento-app
    build:
      context: .
    volumes:
      - ./magento2:/var/www/html/magento2
    ports:
      - "9000:9000"

  server:
    image: nginx:latest
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./magento2:/var/www/html/magento2
      - ./magento.conf:/etc/nginx/conf.d/magento.conf
      - ./services/nginx_log:/var/log/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf

    # command: rm -f /etc/nginx/conf.d/
  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./services/es_data:/var/lib/elasticsearch/data
      - ./services/es_log:/var/log/elasticsearch
    ports:
      - 9200:9200

  db:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    command: ["--log_bin_trust_function_creators=1"]
    volumes:
      - ./services/mysql_data:/var/lib/mysql
      - ./services/mysql_log:/var/log/mysql
    ports:
      - 3306:3306
